export const PATH = {
  HOME: '/',
  SIGNIN: '/sign-in',
  SIGNUP: '/sign-up',
  MYPLAN: '/my-plan',
  PLAN_DETAIL: '/plan-detail',
  SEARCH: '/search',
  SHAREDPLAN: '/shared-plan',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  CALLBACK: '/auth/callback',
  PLAN_NEW: '/plan-detail/new',
  ACCOUNT: '/account',
  BOOKMARKS: '/bookmarks',
  LIKES: '/likes',
  COMMENTS: '/comments',
  CATEGORIES: '/categories',
  RESERVATIONS: '/reservations',
  TICKET: '/air-ticket',
} as const;
