export const DEPARTURE_LIST = [
  { label: '부산', value: 'PUS' },
  { label: '김포', value: 'GMP' },
  { label: '인천', value: 'ICN' },
  { label: '광주', value: 'KWJ' },
  { label: '무안', value: 'MWX' },
  { label: '군산', value: 'KUV' },
  { label: '대구', value: 'TAE' },
  { label: '진주', value: 'HIN' },
  { label: '여수', value: 'RSU' },
  { label: '울산', value: 'USN' },
  { label: '원주', value: 'WJU' },
  { label: '청주', value: 'CJJ' },
  { label: '포항', value: 'KPO' },
  { label: '양양', value: 'YNY' },
];
